# -*- coding: utf-8 -*-
"""END EXMA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GTW-1YQpE8ulTjrHibDEY52YIxUrlXxZ
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,r2_score
from sklearn import tree

data=load_iris()
x=data.data
y=data.target

df=pd.DataFrame(x,columns=data.feature_names)
df['Species']=pd.Categorical.from_codes(y,data.target_names)
print(df['Species'].value_counts())
df.info()
df.describe()
df.isnull().sum()

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=4)
clf=DecisionTreeClassifier(random_state=42)
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)

accuracy=accuracy_score(y_test,y_pred)
print("accuracy_score:",accuracy)
r2=r2_score(y_test,y_pred)
print("r2_score:",r2)

figure=plt.figure(figsize=(10,10))
tree.plot_tree(clf,filled=True,feature_names=data.feature_names,class_names=data.target_names)
plt.title('Decision Tree Display')
plt.show()